gchroot add key -j

diff --git a/bin/gchroot b/bin/gchroot
--- a/bin/gchroot
+++ b/bin/gchroot
@@ -1,10 +1,10 @@
 #!/bin/sh
-set -e
+JOIN=N
 usage(){ 
 	echo "Usage:
   ${0##*/} [chroot path]"
 	cat <<EOF
-
+  -n    no join chroot enviroment 
   -h    Show help options
 
 Version: 0.4.1
@@ -12,21 +12,40 @@ Licence: GNU GPL version 3 <http://www.gnu.org/licenses/gpl.html>
 EOF
 }
 
-if [ "$#" -eq 0 ] || [ "$1" = "-h" ];then
-  usage
+mount_chroot(){
+  if ! mountpoint -q "$1/dev"  && test -d "$1/dev";then mount /dev $1/dev -o bind,nosuid,noexec;fi
+  if ! mountpoint -q "$1/proc" && test -d "$1/proc";then mount -t proc proc "$1/proc" -o nosuid,noexec,nodev;fi 
+  if ! mountpoint -q "$1/sys"  && test -d "$1/sys";then mount -t sysfs sys "$1/sys" -o nosuid,noexec,nodev;fi
+  if ! mountpoint -q "$1/tmp"  && test -d "$1/tmp";then mount /tmp "$1/tmp" -o bind,nosuid,nodev;fi
+}
+
+if [ "$#" -eq 0 ];then usage; exit 1; fi
+
+ARGS=$(getopt -n $(basename "$0") -o 'hj' -- "$@")
+
+eval set -- "$ARGS"
+
+while [ "$1" != -- ]; do
+    case "$1" in
+        -j) JOIN=Y;;
+        -h) usage;exit 0;;
+    esac
+    shift
+done
+shift $(expr $# - 1)
+
+mpath=$(echo $1 | sed 's/\/$//')
+if ! test -d $mpath ;then echo "Error: no mount point ${mpath}"; exit 1;fi
+mount_chroot $mpath
+if test -d "${mpath}/etc/"; then
+  cp /etc/resolv.conf $mpath/etc/resolv.conf
+else
+  echo "Error: no directory "${mpath}/etc/""
   exit 1
 fi
 
-mpath=$(echo $1 | sed 's/\/$//')
+if [ $JOIN = "Y" ];then
+  chroot $mpath  /bin/su -
+fi
 
-mount_chroot(){
-  if ! mountpoint -q "$1/dev" ;then mount /dev $1/dev -o bind,nosuid,noexec;fi
-  if ! mountpoint -q "$1/proc";then mount -t proc proc "$1/proc" -o nosuid,noexec,nodev;fi 
-  if ! mountpoint -q "$1/sys" ;then mount -t sysfs sys "$1/sys" -o nosuid,noexec,nodev;fi
-  if ! mountpoint -q "$1/tmp" ;then mount /tmp "$1/tmp" -o bind,nosuid,nodev;fi
-}
-
-mount_chroot $mpath
-cp /etc/resolv.conf $1/etc/resolv.conf
-chroot $mpath  /bin/su -
 
